SET FOREIGN_KEY_CHECKS=0;




CREATE TABLE BlogPosts
(
	Id INTEGER NOT NULL AUTO_INCREMENT,
	Title VARCHAR(255) NOT NULL,
	PublishStatus VARCHAR(1) NOT NULL,
	RewriteID VARCHAR(50),
	Author VARCHAR(255) NOT NULL,
	ContentType VARCHAR(1) NOT NULL,
	Content VARCHAR(0) NOT NULL,
	CreateDate DATETIME NOT NULL,
	ViewCount INTEGER NOT NULL,
	PRIMARY KEY (Id)

) 
;


CREATE TABLE Comments
(
	Id INTEGER NOT NULL AUTO_INCREMENT,
	Author VARCHAR(255) NOT NULL,
	CreateDate DATETIME NOT NULL,
	CommentText VARCHAR(0) NOT NULL,
	BlogPost_Id INTEGER NOT NULL,
	PRIMARY KEY (Id),
	INDEX IX_FK_BlogPostComment (BlogPost_Id ASC)

) 
;


CREATE TABLE Tags
(
	Id INTEGER NOT NULL AUTO_INCREMENT,
	TagValue VARCHAR(50) NOT NULL,
	BlogPost_Id INTEGER NOT NULL,
	PRIMARY KEY (Id),
	INDEX IX_FK_BlogPostTag (BlogPost_Id ASC)

) 
;



SET FOREIGN_KEY_CHECKS=1;


ALTER TABLE Comments ADD CONSTRAINT FK_BlogPostComment 
	FOREIGN KEY (BlogPost_Id) REFERENCES BlogPosts (Id)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE Tags ADD CONSTRAINT FK_BlogPostTag 
	FOREIGN KEY (BlogPost_Id) REFERENCES BlogPosts (Id)
	ON DELETE RESTRICT ON UPDATE RESTRICT
;
